feat: fe-a-2021-q1-q30
Luzefiru/philnits-vault pull request #13
Opened 2024-10-18 18:17 UTC by jonathan-christ

Added:
- Q1-Q30 flashcards of PhilNits FE April 2021 AM Questions
  - w/ corresponding pictures
- `#software` tag

2024-10-18 18:19 UTC, jonathan-christ commented
These additional commits might be because of the frequent rebasing

2024-10-18 18:39 UTC, Anjeelow approved these changes

2024-10-19 02:18 UTC, Luzefiru requested changes
Delete the Various Complements plugin please.

2024-10-19 03:46 UTC, Samuel-Bonghanoy requested changes

2024-10-19 03:46 UTC, Samuel-Bonghanoy commented on .obsidian/plugins/various-complements/main.js
we deleted this plugin iirc

2024-10-19 07:38 UTC, jonathan-christ commented on .obsidian/plugins/various-complements/main.js
oks fixed

2024-10-19 07:47 UTC, Luzefiru approved these changes
LGTM.

2024-10-19 08:03 UTC, Samuel-Bonghanoy approved these changes
Noice LGTM after fixing the readme conflicts

2024-10-19 08:08 UTC, Samuel-Bonghanoy approved these changes
LGTM part 2

2024-10-19 08:08 UTC, merged